#pragma kernel CSMain

RWStructuredBuffer<float4x4> MatrixBuffer;
RWStructuredBuffer<float4> MatrixRowBuffer;
float4x4 mat;

[numthreads(64, 1, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4x4 m = MatrixBuffer[id.x];

    float4 row0 = MatrixRowBuffer[id.x + 0];
    float4 row1 = MatrixRowBuffer[id.x + 1];
    float4 row2 = MatrixRowBuffer[id.x + 2];
    float4 row3 = MatrixRowBuffer[id.x + 3];

    float4x4 matFromRow = float4x4(row0, row1, row2, row3); // 列で代入されてる？？
    float4x4 matFromComponent = float4x4(row0.x, row0.y, row0.z, row0.w, row1.x, row1.y, row1.z, row1.w, row2.x, row2.y, row2.z, row2.w, row3.x, row3.y, row3.z, row3.w);

    /*
    float m00 = m[0][0];
    float m01 = m[0][1]; m01 = 99;
    float m02 = m[0][2];
    float m03 = m[0][3];

    float m10 = m[1][0];
    float m11 = m[1][1];
    float m12 = m[1][2];
    float m13 = m[1][3];

    float m20 = m[2][0];
    float m21 = m[2][1];
    float m22 = m[2][2];
    float m23 = m[2][3];

    float m30 = m[3][0];
    float m31 = m[3][1];
    float m32 = m[3][2];
    float m33 = m[3][3];

    float4x4 newMat = float4x4(
        m00, m01, m02, m03,
        m10, m11, m12, m13,
        m20, m21, m22, m23,
        m30, m31, m32, m33);

        MatrixBuffer[id.x] = newMat;*/

    matFromComponent._m10 += 99; // 1行0列目

    MatrixRowBuffer[id.x + 0] = matFromComponent[3];
    
    MatrixBuffer[id.x] = matFromComponent;
}
